### ISSUE TITLE
stream方式验证

### ISSUE THREAD

**Issue by xnxz123** [Pitayafruits/springboot-dify-api#1]
postman中验证stream格式的，感觉响应速度还是有点慢，也没有呈现流式打字机的效果

**Comment by Pitayafruits** [comment]
dify的这个流式确实效果不太好，我建议要想追求打字机效果，就直接阻塞式调用，然后在前端自己实现打字机效果

**Comment by martin-bian** [comment]
刚刚看到你的项目，你都用了Flux了，pproduce改成text/stream不就行了嘛，流调用不就是打字机效果嘛
